# Generated by Django 5.1.4 on 2024-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=64)),
                ('mobile_number', models.IntegerField()),
                ('birthday', models.IntegerField()),
            ],
        ),
    ]
